# Generated by Django 5.1.4 on 2024-12-20 06:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("posts", "0003_post_test"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="post",
            name="test",
        ),
    ]
